// countries.js

const options = {
  ageRange: [
    { id: 1, value: "3-6" },
    { id: 2, value: "7-10" },
    { id: 3, value: "11-15" },
    { id: 4, value: "15-18" },
    { id: 5, value: "19-25" },
    { id: 6, value: "26-30" },
    { id: 7, value: "31-40" },
    { id: 8, value: "41-50" },
    { id: 9, value: "51-60" },
    { id: 10, value: "60 and above" },
  ],

  state: [
    { id: 1, value: "Oyo" },
    { id: 2, value: "Ogun" },
  ],

  teachingFormates: [
    { id: 1, value: "in-person" },
    { id: 2, value: "group" },
  ],

  timing: [
    { id: 1, value: "0:00" },
    { id: 2, value: "1:00" },
    { id: 3, value: "2:00" },
    { id: 4, value: "3:00" },
    { id: 5, value: "4:00" },
    { id: 6, value: "5:00" },
    { id: 7, value: "6:00" },
    { id: 8, value: "7:00" },
    { id: 9, value: "8:00" },
    { id: 10, value: "9:00" },
    { id: 11, value: "10:00" },
    { id: 12, value: "11:00" },
    { id: 13, value: "12:00" },
    { id: 14, value: "13:00" },
    { id: 15, value: "14:00" },
    { id: 16, value: "15:00" },
    { id: 17, value: "16:00" },
    { id: 18, value: "17:00" },
    { id: 19, value: "18:00" },
    { id: 20, value: "19:00" },
    { id: 21, value: "20:00" },
    { id: 22, value: "21:00" },
    { id: 23, value: "22:00" },
    { id: 24, value: "23:00" },
    { id: 25, value: "24:00" },
  ],

  classDurations: [
    { id: 1, value: "1 hour" },
    { id: 2, value: "2 hours" },
    { id: 3, value: "3 hours" },
    { id: 4, value: "4 hours" },
    { id: 5, value: "5 hours and above" },
  ],

  contractDurations: [
    { id: 1, value: "1 week" },
    { id: 2, value: "2-3 weeks" },
    { id: 3, value: "1 month" },
    { id: 4, value: "2-3 months" },
    { id: 5, value: "4-6 months" },
    { id: 6, value: "7-11 months" },
    { id: 7, value: "12 months and above" },
  ],

  genders: ["Male", "Female", "Others", "choose not to say"],

  modeOfTeachings: [
    { id: 1, value: "Online" },
    { id: 2, value: "In-person" },
    { id: 3, value: "Both" },
  ],

  religions: [
    { id: 1, value: "Christian" },
    { id: 2, value: "Muslim" },
    { id: 3, value: "Indigenous" },
  ],

  accessToLaptop: [
    { id: 1, value: "Yes, I have a personal computer" },
    {
      id: 2,
      value:
        "Yes, I have access to a laptop anytime I need it, but it is not my own",
    },
    { id: 3, value: "No, I do not have either" },
    { id: 4, value: "Not sure" },
  ],

  willingToInvest: [
    { id: 1, value: "Yes, I am willing to invest in the necessary equipment" },
    {
      id: 2,
      value: "No, I am not willing to invest in the necessary equipment",
    },
    { id: 3, value: "Unsure" },
  ],

  isStrongInternet: [
    { id: 1, value: "Yes" },
    { id: 2, value: "No" },
  ],

  teachingMethods: [
    { id: 1, value: "Lectures" },
    { id: 2, value: "Discussions" },
    { id: 3, value: "Hands-on Activities and Experiments" },
    { id: 4, value: "Group Work and Collaboration" },
    { id: 5, value: "Case Studies" },
    { id: 6, value: "Multimedia and Technology Integration" },
    { id: 7, value: "Project-Based Learning" },
    { id: 8, value: "Inquiry-Based Learning" },
    { id: 9, value: "Flipped Classroom" },
    { id: 10, value: "Differentiated Instruction" },
  ],

  comfortabilityWithOnlineTeachingSoftwares: [
    { id: 1, value: "Very comfortable" },
    { id: 2, value: "Comfortable" },
    { id: 3, value: "Neutral" },
    { id: 4, value: "Uncomfortable" },
    { id: 5, value: "Very uncomfortable" },
  ],

  preferredPaymentPlan: [
    { id: 1, value: "Pay-per-Hour" },
    { id: 2, value: "Pay-per-week" },
    { id: 3, value: "Pay-per-Month" },
    { id: 4, value: "Pay-per-school session" },
    { id: 5, value: "Subscription-Based" },
    { id: 6, value: "Package-Based" },
  ],

  yesorno: ["Yes", "No"],

  agree: ["Agreed", "Disagreed"],

  nysc: ["Completed", "Ongoing", "Waiting for posting", "Still in school"],

  roles: [
    "Frontend developer",
    "Backend developer",
    "Mobile App developer",
    "Product designer",
  ],

  levels: [
    { id: 1, value: "Entry-Level" },
    { id: 2, value: "Mid-Level" },
    { id: 3, value: "Experienced-Level (Senior)" },
    { id: 4, value: "Lead-Level" },
  ],

  yearsOfTeachingExperience: [
    { id: 0, value: "No Experience" },
    { id: 1, value: "0-1year" },
    { id: 2, value: "1-3years" },
    { id: 3, value: "4-6years" },
    { id: 4, value: "7-10years" },
    { id: 5, value: "11-15years" },
    { id: 6, value: "16-25years" },
    { id: 7, value: "17-36years" },
    { id: 8, value: "37years and above" },
  ],

  qualifications: [
    "Doctorate (Ph.D., Ed.D., etc.)",
    "Professional Degree ((M.D., J.D., Pharm.D., D.D.S. etc)",
    "Master's Degree",
    "Bachelor's Degree",
    "Associate's Degree",
    "Higher National Diploma (HND)",
    "Ordinary National Diploma (OND)",
    "Professional Certifications (ICAN, NBA, NIM, etc)",
    "National Certificate of Education (NCE)",
  ],

  countries: [
    { name: "Afghanistan", code: "AF" },
    { name: "Åland Islands", code: "AX" },
    { name: "Albania", code: "AL" },
    { name: "Algeria", code: "DZ" },
    { name: "American Samoa", code: "AS" },
    { name: "AndorrA", code: "AD" },
    { name: "Angola", code: "AO" },
    { name: "Anguilla", code: "AI" },
    { name: "Antarctica", code: "AQ" },
    { name: "Antigua and Barbuda", code: "AG" },
    { name: "Argentina", code: "AR" },
    { name: "Armenia", code: "AM" },
    { name: "Aruba", code: "AW" },
    { name: "Australia", code: "AU" },
    { name: "Austria", code: "AT" },
    { name: "Azerbaijan", code: "AZ" },
    { name: "Bahamas", code: "BS" },
    { name: "Bahrain", code: "BH" },
    { name: "Bangladesh", code: "BD" },
    { name: "Barbados", code: "BB" },
    { name: "Belarus", code: "BY" },
    { name: "Belgium", code: "BE" },
    { name: "Belize", code: "BZ" },
    { name: "Benin", code: "BJ" },
    { name: "Bermuda", code: "BM" },
    { name: "Bhutan", code: "BT" },
    { name: "Bolivia", code: "BO" },
    { name: "Bosnia and Herzegovina", code: "BA" },
    { name: "Botswana", code: "BW" },
    { name: "Bouvet Island", code: "BV" },
    { name: "Brazil", code: "BR" },
    { name: "British Indian Ocean Territory", code: "IO" },
    { name: "Brunei Darussalam", code: "BN" },
    { name: "Bulgaria", code: "BG" },
    { name: "Burkina Faso", code: "BF" },
    { name: "Burundi", code: "BI" },
    { name: "Cambodia", code: "KH" },
    { name: "Cameroon", code: "CM" },
    { name: "Canada", code: "CA" },
    { name: "Cape Verde", code: "CV" },
    { name: "Cayman Islands", code: "KY" },
    { name: "Central African Republic", code: "CF" },
    { name: "Chad", code: "TD" },
    { name: "Chile", code: "CL" },
    { name: "China", code: "CN" },
    { name: "Christmas Island", code: "CX" },
    { name: "Cocos (Keeling) Islands", code: "CC" },
    { name: "Colombia", code: "CO" },
    { name: "Comoros", code: "KM" },
    { name: "Congo", code: "CG" },
    { name: "Congo, The Democratic Republic of the", code: "CD" },
    { name: "Cook Islands", code: "CK" },
    { name: "Costa Rica", code: "CR" },
    { name: "Cote D'Ivoire", code: "CI" },
    { name: "Croatia", code: "HR" },
    { name: "Cuba", code: "CU" },
    { name: "Cyprus", code: "CY" },
    { name: "Czech Republic", code: "CZ" },
    { name: "Denmark", code: "DK" },
    { name: "Djibouti", code: "DJ" },
    { name: "Dominica", code: "DM" },
    { name: "Dominican Republic", code: "DO" },
    { name: "Ecuador", code: "EC" },
    { name: "Egypt", code: "EG" },
    { name: "El Salvador", code: "SV" },
    { name: "Equatorial Guinea", code: "GQ" },
    { name: "Eritrea", code: "ER" },
    { name: "Estonia", code: "EE" },
    { name: "Ethiopia", code: "ET" },
    { name: "Falkland Islands (Malvinas)", code: "FK" },
    { name: "Faroe Islands", code: "FO" },
    { name: "Fiji", code: "FJ" },
    { name: "Finland", code: "FI" },
    { name: "France", code: "FR" },
    { name: "French Guiana", code: "GF" },
    { name: "French Polynesia", code: "PF" },
    { name: "French Southern Territories", code: "TF" },
    { name: "Gabon", code: "GA" },
    { name: "Gambia", code: "GM" },
    { name: "Georgia", code: "GE" },
    { name: "Germany", code: "DE" },
    { name: "Ghana", code: "GH" },
    { name: "Gibraltar", code: "GI" },
    { name: "Greece", code: "GR" },
    { name: "Greenland", code: "GL" },
    { name: "Grenada", code: "GD" },
    { name: "Guadeloupe", code: "GP" },
    { name: "Guam", code: "GU" },
    { name: "Guatemala", code: "GT" },
    { name: "Guernsey", code: "GG" },
    { name: "Guinea", code: "GN" },
    { name: "Guinea-Bissau", code: "GW" },
    { name: "Guyana", code: "GY" },
    { name: "Haiti", code: "HT" },
    { name: "Heard Island and Mcdonald Islands", code: "HM" },
    { name: "Holy See (Vatican City State)", code: "VA" },
    { name: "Honduras", code: "HN" },
    { name: "Hong Kong", code: "HK" },
    { name: "Hungary", code: "HU" },
    { name: "Iceland", code: "IS" },
    { name: "India", code: "IN" },
    { name: "Indonesia", code: "ID" },
    { name: "Iran, Islamic Republic Of", code: "IR" },
    { name: "Iraq", code: "IQ" },
    { name: "Ireland", code: "IE" },
    { name: "Isle of Man", code: "IM" },
    { name: "Israel", code: "IL" },
    { name: "Italy", code: "IT" },
    { name: "Jamaica", code: "JM" },
    { name: "Japan", code: "JP" },
    { name: "Jersey", code: "JE" },
    { name: "Jordan", code: "JO" },
    { name: "Kazakhstan", code: "KZ" },
    { name: "Kenya", code: "KE" },
    { name: "Kiribati", code: "KI" },
    { name: "Korea, Democratic People'S Republic of", code: "KP" },
    { name: "Korea, Republic of", code: "KR" },
    { name: "Kuwait", code: "KW" },
    { name: "Kyrgyzstan", code: "KG" },
    { name: "Lao People'S Democratic Republic", code: "LA" },
    { name: "Latvia", code: "LV" },
    { name: "Lebanon", code: "LB" },
    { name: "Lesotho", code: "LS" },
    { name: "Liberia", code: "LR" },
    { name: "Libyan Arab Jamahiriya", code: "LY" },
    { name: "Liechtenstein", code: "LI" },
    { name: "Lithuania", code: "LT" },
    { name: "Luxembourg", code: "LU" },
    { name: "Macao", code: "MO" },
    { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
    { name: "Madagascar", code: "MG" },
    { name: "Malawi", code: "MW" },
    { name: "Malaysia", code: "MY" },
    { name: "Maldives", code: "MV" },
    { name: "Mali", code: "ML" },
    { name: "Malta", code: "MT" },
    { name: "Marshall Islands", code: "MH" },
    { name: "Martinique", code: "MQ" },
    { name: "Mauritania", code: "MR" },
    { name: "Mauritius", code: "MU" },
    { name: "Mayotte", code: "YT" },
    { name: "Mexico", code: "MX" },
    { name: "Micronesia, Federated States of", code: "FM" },
    { name: "Moldova, Republic of", code: "MD" },
    { name: "Monaco", code: "MC" },
    { name: "Mongolia", code: "MN" },
    { name: "Montserrat", code: "MS" },
    { name: "Morocco", code: "MA" },
    { name: "Mozambique", code: "MZ" },
    { name: "Myanmar", code: "MM" },
    { name: "Namibia", code: "NA" },
    { name: "Nauru", code: "NR" },
    { name: "Nepal", code: "NP" },
    { name: "Netherlands", code: "NL" },
    { name: "Netherlands Antilles", code: "AN" },
    { name: "New Caledonia", code: "NC" },
    { name: "New Zealand", code: "NZ" },
    { name: "Nicaragua", code: "NI" },
    { name: "Niger", code: "NE" },
    { name: "Nigeria", code: "NG" },
    { name: "Niue", code: "NU" },
    { name: "Norfolk Island", code: "NF" },
    { name: "Northern Mariana Islands", code: "MP" },
    { name: "Norway", code: "NO" },
    { name: "Oman", code: "OM" },
    { name: "Pakistan", code: "PK" },
    { name: "Palau", code: "PW" },
    { name: "Palestinian Territory, Occupied", code: "PS" },
    { name: "Panama", code: "PA" },
    { name: "Papua New Guinea", code: "PG" },
    { name: "Paraguay", code: "PY" },
    { name: "Peru", code: "PE" },
    { name: "Philippines", code: "PH" },
    { name: "Pitcairn", code: "PN" },
    { name: "Poland", code: "PL" },
    { name: "Portugal", code: "PT" },
    { name: "Puerto Rico", code: "PR" },
    { name: "Qatar", code: "QA" },
    { name: "Reunion", code: "RE" },
    { name: "Romania", code: "RO" },
    { name: "Russian Federation", code: "RU" },
    { name: "RWANDA", code: "RW" },
    { name: "Saint Helena", code: "SH" },
    { name: "Saint Kitts and Nevis", code: "KN" },
    { name: "Saint Lucia", code: "LC" },
    { name: "Saint Pierre and Miquelon", code: "PM" },
    { name: "Saint Vincent and the Grenadines", code: "VC" },
    { name: "Samoa", code: "WS" },
    { name: "San Marino", code: "SM" },
    { name: "Sao Tome and Principe", code: "ST" },
    { name: "Saudi Arabia", code: "SA" },
    { name: "Senegal", code: "SN" },
    { name: "Serbia and Montenegro", code: "CS" },
    { name: "Seychelles", code: "SC" },
    { name: "Sierra Leone", code: "SL" },
    { name: "Singapore", code: "SG" },
    { name: "Slovakia", code: "SK" },
    { name: "Slovenia", code: "SI" },
    { name: "Solomon Islands", code: "SB" },
    { name: "Somalia", code: "SO" },
    { name: "South Africa", code: "ZA" },
    { name: "South Georgia and the South Sandwich Islands", code: "GS" },
    { name: "Spain", code: "ES" },
    { name: "Sri Lanka", code: "LK" },
    { name: "Sudan", code: "SD" },
    { name: "Suriname", code: "SR" },
    { name: "Svalbard and Jan Mayen", code: "SJ" },
    { name: "Swaziland", code: "SZ" },
    { name: "Sweden", code: "SE" },
    { name: "Switzerland", code: "CH" },
    { name: "Syrian Arab Republic", code: "SY" },
    { name: "Taiwan, Province of China", code: "TW" },
    { name: "Tajikistan", code: "TJ" },
    { name: "Tanzania, United Republic of", code: "TZ" },
    { name: "Thailand", code: "TH" },
    { name: "Timor-Leste", code: "TL" },
    { name: "Togo", code: "TG" },
    { name: "Tokelau", code: "TK" },
    { name: "Tonga", code: "TO" },
    { name: "Trinidad and Tobago", code: "TT" },
    { name: "Tunisia", code: "TN" },
    { name: "Turkey", code: "TR" },
    { name: "Turkmenistan", code: "TM" },
    { name: "Turks and Caicos Islands", code: "TC" },
    { name: "Tuvalu", code: "TV" },
    { name: "Uganda", code: "UG" },
    { name: "Ukraine", code: "UA" },
    { name: "United Arab Emirates", code: "AE" },
    { name: "United Kingdom", code: "GB" },
    { name: "United States", code: "US" },
    { name: "United States Minor Outlying Islands", code: "UM" },
    { name: "Uruguay", code: "UY" },
    { name: "Uzbekistan", code: "UZ" },
    { name: "Vanuatu", code: "VU" },
    { name: "Venezuela", code: "VE" },
    { name: "Viet Nam", code: "VN" },
    { name: "Virgin Islands, British", code: "VG" },
    { name: "Virgin Islands, U.S.", code: "VI" },
    { name: "Wallis and Futuna", code: "WF" },
    { name: "Western Sahara", code: "EH" },
    { name: "Yemen", code: "YE" },
    { name: "Zambia", code: "ZM" },
    { name: "Zimbabwe", code: "ZW" },
  ],
}

export default options
